name: flake8

on:
  push:
    branches:
      - 'master'

jobs:
  flake8:
    name: Use flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8

      - name: Lint with flake8
        run: |
              flake8 -v --max-line-length=150
